Attribute VB_Name = "cderr"
Option Explicit


Public Const CDERR_DIALOGFAILURE As Long = &HFFFF

Public Const CDERR_GENERALCODES As Long = &H0
Public Const CDERR_STRUCTSIZE As Long = &H1
Public Const CDERR_INITIALIZATION As Long = &H2
Public Const CDERR_NOTEMPLATE As Long = &H3
Public Const CDERR_NOHINSTANCE As Long = &H4
Public Const CDERR_LOADSTRFAILURE As Long = &H5
Public Const CDERR_FINDRESFAILURE As Long = &H6
Public Const CDERR_LOADRESFAILURE As Long = &H7
Public Const CDERR_LOCKRESFAILURE As Long = &H8
Public Const CDERR_MEMALLOCFAILURE As Long = &H9
Public Const CDERR_MEMLOCKFAILURE As Long = &HA
Public Const CDERR_NOHOOK As Long = &HB
Public Const CDERR_REGISTERMSGFAIL As Long = &HC

Public Const PDERR_PRINTERCODES As Long = &H1000
Public Const PDERR_SETUPFAILURE As Long = &H1001
Public Const PDERR_PARSEFAILURE As Long = &H1002
Public Const PDERR_RETDEFFAILURE As Long = &H1003
Public Const PDERR_LOADDRVFAILURE As Long = &H1004
Public Const PDERR_GETDEVMODEFAIL As Long = &H1005
Public Const PDERR_INITFAILURE As Long = &H1006
Public Const PDERR_NODEVICES As Long = &H1007
Public Const PDERR_NODEFAULTPRN As Long = &H1008
Public Const PDERR_DNDMMISMATCH As Long = &H1009
Public Const PDERR_CREATEICFAILURE As Long = &H100A
Public Const PDERR_PRINTERNOTFOUND As Long = &H100B
Public Const PDERR_DEFAULTDIFFERENT As Long = &H100C

Public Const CFERR_CHOOSEFONTCODES As Long = &H2000
Public Const CFERR_NOFONTS As Long = &H2001
Public Const CFERR_MAXLESSTHANMIN As Long = &H2002

Public Const FNERR_FILENAMECODES As Long = &H3000
Public Const FNERR_SUBCLASSFAILURE As Long = &H3001
Public Const FNERR_INVALIDFILENAME As Long = &H3002
Public Const FNERR_BUFFERTOOSMALL As Long = &H3003

Public Const FRERR_FINDREPLACECODES As Long = &H4000
Public Const FRERR_BUFFERLENGTHZERO As Long = &H4001

Public Const CCERR_CHOOSECOLORCODES As Long = &H5000
